### PR TITLE
Fix the resolution issues

### PR DESCRIPTION
**Pull request by herrwusel**
Fixing issue https://github.com/mcuadros/OctoPrint-TFT/issues/8

### CODE REVIEW

**Comment by mcuadros** [comment]
Thanks!

**Comment by littleferris** [comment]
Was this ever actually implemented? Cause I’m still getting the resolution issue.?

**Comment by SegaBoy64** [comment]
> Was this ever actually implemented? Cause I’m still getting the resolution issue.?

Agree - I cant seem to get OctoPrint-TFT to work on the 7" screen no matter what configuration I attempt.

**Comment by herrwusel** [comment]
Are you downloading the latest release or are you building this yourself? The latest release doesn'T has the change yet.

**Pull request merged**
